import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "./components/_utils/auth-context";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
 
// const Layout = ({ children }) => {
//   return <AuthContextProvider>{children}</AuthContextProvider>;
// };
 
// export default Layout;